### ISSUE TITLE
Troubleshooting installation problem

### ISSUE THREAD

**Issue by csajedi** [ThomasTJdev/nim_websitecreator#112]
Hi, I've been trying to get this working in my dev environment and so far the nimble installation process, vagrant, build from source and docker process have all failed. After some fiddling I've come to the point where following the install video for building it( #100) and from the dockerfile-based installation I get this error:

> Hint: webp [Processing]
/nim_websitecreator/nimwcpkg/nimwc_main.nim(39, 39) Warning: Firejail is Disabled, Running Unsecure. [User]
/Users/travis/build/nim-lang/nightlies/nim/e7471cebae2a404f3e4239f199f5a0c422484aac/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: /Users/travis/build/nim-lang/nightlies/nim/e7471cebae2a404f3e4239f199f5a0c422484aac/compiler/vm.nim(706, 16) `nfIsRef in regs[ra].node.flags`  [AssertionError]
 Compile Error

What can I do to get around this? I have been trying with nim 0.20.0

**Comment by juancarlospaco** [comment]
Try with `0.19.6` :grey_question: 
I mean by that traceback you are trying with Nim `devel` thats unstable, use a `stable` channel.

**Comment by csajedi** [comment]
when I used `choosenim stable it moved me to 0.20.0`, but I tried now with `0.19.6` and got the same error from docker devops. However I am now able to progress with method 1b: clone and compile to get to serving nimwc in localhost. I may investigate further with docker after I've played with nimwc to gain familiarity. I am pretty new to nim, just finished the only Nim book and wanted to dive right in.

**Comment by juancarlospaco** [comment]
Nim is preparing for v`1.0` so they changed some APIs, that wanted to change for a long time now,
because is the latest opportunities to change the API before `1.0`, so we can say is just casual,
also I am not a Docker expert, but often find easier to just clone and compile it, 
compared to doing the Docker dance, but is also Ok if you want to use Docker too,
with `choosenim` you can quickly change versions of Nim, good to read that you got it working,
the issues are for that, and we are working on improving the code, welcome aboard.
:slightly_smiling_face:

**Comment by juancarlospaco** [comment]
Assuming it worked Ok, since OP said its compiling.
:slightly_smiling_face:
