### ISSUE TITLE
-d:rc Vs -f

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_websitecreator#60]
### Bug Short Description:

`-d:rc` is not the same as vanilla `-f` :grey_question: 
Nim help says `-f, --forceBuild    Force rebuilding of all modules`.
Should we pass `-f` instead of our custom `-d:rc` :grey_question: 

### Operating System:
*Choose 1 or more. Mark the checkbox it with an `X`.*
- [x] Other or Unknown or Unsupported.

### Bug Severity:
*Choose only 1. Mark the checkbox it with an `X`.*
- [X] Low, Minor, Aesthetic, Small, Detail, Trivial.
- [ ] Medium, Normal, Standard.
- [ ] High, Important, Major.
- [ ] Critical, Catastrophic, Epic Fail.
- [ ] Other or Unknown.

## Version
*Semantic Version of this software the Bug Reproduces into. Type in the Version Number*
```
    5.0.0
```

**Comment by ThomasTJdev** [comment]
I have no opinion about the syntax: `rc` or `f`. But `-f` will not do anything different than `rc`? We still need to manually catch it and recompile, right?

**Comment by juancarlospaco** [comment]
Both do the same.
But if we use a custom `-d:rc` we have to document it, maintain it, etc.
We should pass `-f` to the `nimwc_main` and it should do the same as `-d:rc` theoretically.

**Comment by ThomasTJdev** [comment]
I'm not totally sure, that I understand.

`-d:rc` does only tell `nimwc.nim`'s proc `startupCheck()` to compile `nimwc_main.nim`. I can't see how passing `-f` will solve that since `nimwc_main` is not a module, but an individual file we specify when to compile.
https://github.com/ThomasTJdev/nim_websitecreator/blob/37c933c7f65ca451e956b8728a6c7d084f3ac0f8/nimwc.nim#L224-L228

**Comment by juancarlospaco** [comment]
Oh, maybe you are right.
