### ISSUE TITLE
Check folder permission

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#65]
When starting `files_efs` is trying create the standard dirs. If the user does not have access, nimwc will restart and keep trying. Inform user and force a full `quit()`.

**Comment by juancarlospaco** [comment]
This is by definition, Defensive programming, it should run `when not defined(release)`
IMHO. 
But :+1:  for me.

**Comment by juancarlospaco** [comment]
I was thinking that this might not worth the effort because imagine a server with 100.000 files and folders,
it might looks like NimWC takes years to compile :disappointed: 

I prefer to explicitly say on the documentation that the user must check that the program has permission to write on its own folders, and is kinda expected and obvious anyways.

**Comment by ThomasTJdev** [comment]
1) I was only thinking to check, that the location for `storage` in config.cfg was writable. Not checking the individual files.

2) Just updating the `README.md` is fine and maybe the `config.cfg` with a comment.

**Comment by juancarlospaco** [comment]
Oh, my bad, I was thinking you wanted a full recursive walk of the folder tree.
:slightly_smiling_face: :+1:
